# Homebrew formula for proton-mail-bridge-client
# Users install with: brew install googlarz/tap/proton-mail-bridge-client
# Generated by scripts/homebrew-formula.mjs; do not edit the url/sha256 by hand.

require "language/node"

class ProtonMailBridgeClient < Formula
  desc "Full-featured CLI and Claude Desktop MCP for Proton Mail via Proton Bridge"
  homepage "https://github.com/googlarz/proton-mail-bridge-client"
  url "https://registry.npmjs.org/proton-mail-bridge-client/-/proton-mail-bridge-client-2.5.0.tgz"
  sha256 "abccd258595c9437298e615613a437d065805f671a8eac9fdcae2671f3aa7dae"
  license "MIT"

  # Needs Node >= 24 (package.json engines). Homebrew has no way to state a minimum version for
  # the rolling "node" formula; it currently provides a release that satisfies this.
  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  def caveats
    <<~EOS
      Requires Node.js 24 or newer (brew upgrade node if `node --version` is older).
      Proton Mail Bridge must be running before using this tool.
      Download Bridge at: https://proton.me/mail/bridge

      Required environment variables (add to ~/.zshrc or ~/.bash_profile):
        export PROTONMAIL_USERNAME='you@proton.me'
        export PROTONMAIL_PASSWORD='your-bridge-password'

      Then run: proton-mail-bridge-client status
    EOS
  end

  test do
    output = shell_output("#{bin}/proton-mail-bridge-client --version 2>&1")
    assert_match "2.5.0", output
  end
end
