#!/usr/bin/env node
// Prints (or writes) the Homebrew formula for a PUBLISHED npm version.
//
//   node scripts/homebrew-formula.mjs 2.3.2 [--write homebrew/proton-mail-bridge-client.rb]
//
// The sha256 is computed from the tarball the registry actually serves (never typed by hand: the
// tap once carried a 40-character npm shasum, which is not a valid sha256, so `brew install`
// failed for everyone). The maintainer copies the output to Formula/ in googlarz/homebrew-tap.
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

export function tarballUrl(version) {
  return `https://registry.npmjs.org/proton-mail-bridge-client/-/proton-mail-bridge-client-${version}.tgz`;
}

export async function fetchTarballSha256(version, fetchImpl = fetch) {
  if (!/^\d+\.\d+\.\d+$/.test(version ?? "")) throw new Error(`Expected a version like 2.3.2, got: ${version}`);
  const response = await fetchImpl(tarballUrl(version));
  if (!response.ok) throw new Error(`${tarballUrl(version)} returned HTTP ${response.status} (is ${version} published?)`);
  return createHash("sha256").update(Buffer.from(await response.arrayBuffer())).digest("hex");
}

export function renderFormula({ version, sha256 }) {
  if (!/^[0-9a-f]{64}$/.test(sha256)) throw new Error(`sha256 must be 64 hex characters, got: ${sha256}`);
  return `# Homebrew formula for proton-mail-bridge-client
# Users install with: brew install googlarz/tap/proton-mail-bridge-client
# Generated by scripts/homebrew-formula.mjs; do not edit the url/sha256 by hand.

class ProtonMailBridgeClient < Formula
  desc "Full-featured CLI and Claude Desktop MCP for Proton Mail via Proton Bridge"
  homepage "https://github.com/googlarz/proton-mail-bridge-client"
  url "${tarballUrl(version)}"
  sha256 "${sha256}"
  license "MIT"

  # Needs Node >= 24 (package.json engines). Homebrew has no way to state a minimum version for
  # the rolling "node" formula; it currently provides a release that satisfies this.
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Requires Node.js 24 or newer (brew upgrade node if \`node --version\` is older).
      Proton Mail Bridge must be running before using this tool.
      Download Bridge at: https://proton.me/mail/bridge

      Required environment variables (add to ~/.zshrc or ~/.bash_profile):
        export PROTONMAIL_USERNAME='you@proton.me'
        export PROTONMAIL_PASSWORD='your-bridge-password'

      Then run: proton-mail-bridge-client status
    EOS
  end

  test do
    output = shell_output("#{bin}/proton-mail-bridge-client --version 2>&1")
    assert_match "${version}", output
  end
end
`;
}

async function main(argv) {
  const writeIndex = argv.indexOf("--write");
  const target = writeIndex === -1 ? undefined : argv[writeIndex + 1];
  if (writeIndex !== -1 && !target) throw new Error("--write requires a path.");
  const version = argv.find((arg, i) => !arg.startsWith("--") && i !== writeIndex + 1);
  const formula = renderFormula({ version, sha256: await fetchTarballSha256(version) });
  if (target) {
    writeFileSync(target, formula);
    console.error(`Wrote ${target}`);
  } else {
    process.stdout.write(formula);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
